AssemblyAITranscriptionPipeline:
  config:
    sample_rate: 16000
    channels: 1
    sample_width: 2
    chunksize_ms: 50
    endpoint_url: "wss://streaming.assemblyai.com/v3/ws"
    use_keywords: true
