defaults:
  - _self_
  - datasets:
    - voxconverse
    - msdwild
    - earnings21
    - ami-ihm
    - ami-sdm
    - american-life-podcast
    - ava-avd
    - timit
    - timit-stitched
  - wandb_config: disabled
  - metrics:
    - wer
    - streaming_latency
    - confirmed_streaming_latency
    - model_timestamp_streaming_latency
    - model_timestamp_confirmed_streaming_latency
    - number_deletions
    - number_substitutions
    - number_insertions
    - wder
    - der
    - jer
    - diarization_purity
    - diarization_purity_coverage_fmeasure
    - diarization_homogeneity
    - scer
    - scmae
    - sca
    - detection_error_rate
    - detection_cost_function
    - detection_precision_recall_fmeasure
