name: Diarization Benchmark
run_name: Diarization Benchmark ${{ github.event.date }} - ${{ github.sha }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 5 * *'  # Every month on the 5th day of the month at 5:00 AM UTC

jobs:
  diarization-benchmark:
    runs-on: M3-Ultra
    strategy:
      fail-fast: false
      matrix:
        dataset:
          - callhome
          - dihard-3
          - ami-ihm
          - ami-sdm
          - earnings21
          - msdwild
          - voxconverse

        pipeline:
          - pyannote
          - pyannote-api
          - aws-diarization
          - deepgram-diarization
        
    uses: ./.github/workflows/run_evaluate.yaml
    env:
      DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}
      PYANNOTE_TOKEN: ${{ secrets.PYANNOTE_API_TOKEN }}
    with:
      dataset: ${{ matrix.dataset }}
      pipeline: ${{ matrix.pipeline }}
      metrics: der jer sca
      wandb_project: diarization-benchmark
      wandb_run_name: ${{ matrix.pipeline }}-${{ matrix.dataset }}-${{ github.event.date }}

  diarization-benchmark-sync-data:
    runs-on: M3-Ultra
    needs: diarization-benchmark
    uses: ./.github/workflows/sync_data.yaml
    with:
      project: diarization-benchmark
      entity: ${{ secrets.WANDB_ENTITY }}
      run_name: ${{ matrix.pipeline }}-${{ matrix.dataset }}-${{ github.event.date }}
      repo_id: openbench-data