name: Sync Data

on:
  workflow_call:
    inputs:
      project:
        type: string
        description: The W&B project to sync data from.
        required: true
      entity:
        type: string
        description: The W&B entity where the project is hosted.
        required: true
      run_name:
        type: string
        description: The W&B run's display name to sync data from. The name should be unique within the project.
        required: true
      repo_id:
        type: string
        description: The Hugging Face repo id to sync data to.
        required: true
  

jobs:
  sync-data:
    runs-on: M3-Ultra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          WANDB_TOKEN: ${{ secrets.WANDB_TOKEN }}

      - name: Sync Data
        shell: bash -el {0}
        run: |
          uv run common/sync_data.py \
            --project ${{ inputs.project }} \
            --entity ${{ inputs.entity }} \
            --run-name ${{ inputs.run_name }} \
            --repo-id ${{ inputs.repo_id }}